name: ShellCheck

on:
  push:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install --yes shellcheck

      - name: Check Bash syntax
        run: bash -n shadowsocks-rust.sh

      - name: Run ShellCheck
        run: shellcheck -x shadowsocks-rust.sh
